name: Build and deploy Node.js app to Azure Web App - scandiwhispers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install
        run: npm install

      - name: npm run build (React)
        run: npm run build

      - name: Zip build directory
        run: cd build && zip -r ../build.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: List files
        run: ls -la

      - name: Unzip build.zip
        run: unzip build.zip -d build

      - name: List unzipped build files
        run: ls -la build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06B94BFD385D465BA3E70F52094FA046 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FB163665FDEE430E98B333386F1CA896 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C0F06D079CF24E1EAE2C5D8009A77DC2 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'scandiwhispers'
          slot-name: 'Production'
          package: build  # NOT build.zip; deploy the unzipped build contents
